#@author <a href="https://github.com/Mredust">Mredust</a>
spring:
  application:
    name: mredust-sql-generator
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: # 数据库地址
    username: root
    password: # 数据库密码


server:
  port: 4091


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: ""

